// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANO5ySxXmZGydIflXJsTDxu5VRQ7tSG1Q',
    appId: '1:476915054673:web:76a7714e05c44b38002070',
    messagingSenderId: '476915054673',
    projectId: 'spems-746c3',
    authDomain: 'spems-746c3.firebaseapp.com',
    storageBucket: 'spems-746c3.firebasestorage.app',
    measurementId: 'G-TBF95XSXER',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDylcMfoyANHEnAn4wuZUKV8BtYp3RK--g',
    appId: '1:476915054673:android:e7c1cb51d685de57002070',
    messagingSenderId: '476915054673',
    projectId: 'spems-746c3',
    storageBucket: 'spems-746c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBspYPVwJlcfRqQWHxLmJqFKAxGydlZEjM',
    appId: '1:476915054673:ios:c8533eb871b41512002070',
    messagingSenderId: '476915054673',
    projectId: 'spems-746c3',
    storageBucket: 'spems-746c3.firebasestorage.app',
    iosClientId: '476915054673-il6gqrulo83p8svns4ba3taqjlmb3o3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.sepmsMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBspYPVwJlcfRqQWHxLmJqFKAxGydlZEjM',
    appId: '1:476915054673:ios:c8533eb871b41512002070',
    messagingSenderId: '476915054673',
    projectId: 'spems-746c3',
    storageBucket: 'spems-746c3.firebasestorage.app',
    iosClientId: '476915054673-il6gqrulo83p8svns4ba3taqjlmb3o3u.apps.googleusercontent.com',
    iosBundleId: 'com.example.sepmsMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANO5ySxXmZGydIflXJsTDxu5VRQ7tSG1Q',
    appId: '1:476915054673:web:1fe290b501158ebf002070',
    messagingSenderId: '476915054673',
    projectId: 'spems-746c3',
    authDomain: 'spems-746c3.firebaseapp.com',
    storageBucket: 'spems-746c3.firebasestorage.app',
    measurementId: 'G-LLGSXXZZRV',
  );
}
